name: Ubuntu SSH

on:
  workflow_dispatch:

jobs:
  build:
    if: github.event.repository.owner.id == github.event.sender.id
    runs-on: ubuntu-20.04
    permissions:
      contents: write
    steps:
      - name: Cleanup
        uses: rokibhasansagar/slimhub_actions@main
      
      - name: Prepare the environment
        run: |
          sudo apt update
          sudo apt -y upgrade
          sudo apt -y install gperf gcc-multilib gcc-10-multilib g++-multilib g++-10-multilib libc6-dev lib32ncurses5-dev x11proto-core-dev libx11-dev tree lib32z-dev libgl1-mesa-dev libxml2-utils xsltproc bc ccache lib32readline-dev lib32z1-dev liblz4-tool libncurses5-dev libsdl1.2-dev libwxgtk3.0-gtk3-dev libxml2 lzop pngcrush schedtool squashfs-tools imagemagick libbz2-dev lzma ncftp qemu-user-static libstdc++-10-dev libncurses5 python ssh wget tmate

      - name: Install build-tools
        run: |
          wget https://android.googlesource.com/platform/prebuilts/build-tools/+archive/refs/heads/master.tar.gz -O ~/master.tar.gz
          tar xf ~/master.tar.gz

      - name: Install gas
        run: |
          mkdir -p gas/linux-x86
          git clone https://android.googlesource.com/platform/prebuilts/gas/linux-x86 ~/gas/linux-x86

      - name: Install clang
        run: |
          mkdir clang-universal8825
          git clone https://github.com/s5e8825/prebuilts_clang_host_linux-x86_clang-universal8825 ~/clang-universal8825

      - name: Running tmate
        run: |
          mkdir script
          git clone https://github.com/xchuzen/ubuntussh/blob/def3ff98ed7a7eca8ba4a73a9211d39daa2526a1/.github/workflows/script.sh
